---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
data:
  cloud-config: |-
    address: "verda-cloud-provider.kube-system.svc.cluster.local:8086"



#cert: "/etc/externalgrpc-client/tls.crt"
#key: "/etc/externalgrpc-client/tls.key"
#cacert: "/etc/externalgrpc-client/ca.crt"
