apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: verda-cloud-provider
  app.kubernetes.io/component: cloud-provider
  app.kubernetes.io/part-of: cluster-autoscaler
